name: student-debt-calc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.109.0
  - uvicorn=0.27.0
  - pandas=2.1.4
  - python-multipart=0.0.6
  - python-dotenv=1.0.0
  - pydantic=2.5.3
  - pip
  - pip:
    - fastapi-cors==0.0.6
